employee/urls.py
from django.urls import path
from . import views


urlpatterns = [
     path('add/', views.add_employee_view, name='add_employee'),
     path('all/', views.employee_list_view, name='employee_list'),
     path('<int:id>/details/', views.employee_details_view, name='view_employee'),
     path('<int:id>/edit/', views.employee_edit_view, name='edit_employee'),
     path('<int:id>/delete/', views.employee_delete_view, name='delete_employee'),
     path('profile/', views.profile_view, name='profile_view'),
]

lms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView
from accounts.forms import LoginForm
from accounts.views import *
import accounts.views
from employee.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('accounts.urls')),
    # path('register/', accounts.views.register, name='register'),
    # path('login/', auth_views.LoginView, {'template_name': 'login.html', 'authentication_form': 'LoginForm'}),
    # path('logout/', auth_views.LogoutView, {'next_page': '/login'}),
    path('employee/', include('employee.urls')),
    path('leave/', include('applyleave.urls')),
    # path('myleave/', include('applyleave.urls')),
    #path('teamleave/', include('applyleave.urls')),
]

employee/models.py
from django.db import models
from django.contrib.auth.models import User
from applyleave.models import LeaveCategory
from datetime import datetime


class Company(models.Model):
    name = models.CharField(max_length=100, unique=True, primary_key=True)

    def __str__(self):
        return self.name


class EmployeeDetails(models.Model):
    empid = models.CharField(max_length=10, unique=True, primary_key=True)
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=75, unique=True)
    company = models.CharField(max_length=50)  # models.ForeignKey(Company, on_delete=models.SET_NULL, null=True)
    designation = models.CharField(max_length=100)
    date_of_joining = models.DateField(null=True, blank=True)
    job_location = models.CharField(max_length=100, default='Goa')
    employment_setup = models.CharField(max_length=50)
    gender = models.CharField(max_length=10)
    marital_status = models.CharField(max_length=20)
    user_type = models.CharField(max_length=20, default='User')
    weekend_day = models.CharField(max_length=2, default=2)
    leave_category = models.CharField(max_length=10)  # models.ForeignKey(LeaveCategory, on_delete=models.CASCADE)
    single_day_entitlement = models.CharField(max_length=5, default=0)
    annual_entitlement = models.CharField(max_length=5, default=0)
    reporting_manager_empid = models.CharField(max_length=10)
    reporting_manager_name = models.CharField(max_length=100)
    reporting_manager_email = models.EmailField(max_length=75)
    date_of_leaving = models.DateField(null=True, blank=True)
    employee_status = models.CharField(max_length=10, default='Active')
    userid = models.IntegerField(null=True, blank=True)
    # password = models.CharField(null=True, blank=True, max_length=128)

    def __str__(self):
        return self.name  # + " - " + self.company


class Location(models.Model):
    job_location = models.CharField(max_length=100, unique=True, primary_key=True)

    def __str__(self):
        return self.job_location


class EmploymentSetup(models.Model):
    employment_setup = models.CharField(max_length=50, unique=True, primary_key=True)

    def __str__(self):
        return self.employment_setup


class Gender(models.Model):
    gender = models.CharField(max_length=20, unique=True, primary_key=True)

    def __str__(self):
        return self.gender


class MaritalStatus(models.Model):
    marital_status = models.CharField(max_length=20, unique=True, primary_key=True)

    def __str__(self):
        return self.marital_status


class UserType(models.Model):
    user_type = models.CharField(max_length=20, unique=True, primary_key=True)

    def __str__(self):
        return self.user_type


class WeekendDay(models.Model):
    weekend_day = models.CharField(max_length=2, unique=True, primary_key=True)

    def __str__(self):
        return self.weekend_day


class EmployeeStatus(models.Model):
    employee_status = models.CharField(max_length=10, unique=True, primary_key=True)

    def __str__(self):
        return self.employee_status

employee/forms.py
from django.forms import ModelForm
from .models import *
from django import forms


class AddEmployeeForm(ModelForm):
    empid = forms.CharField(label='Employee ID', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Employee ID', 'name': 'empid', 'id': 'empid', 'autofocus': 'True'}), required=True, max_length=10)
    name = forms.CharField(label='Name', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name', 'name': 'name', 'id': 'name'}), required=True, max_length=100)
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control', 'type': 'email', 'placeholder': 'Email Address', 'name': 'email', 'id': 'email'}), required=True, max_length=75)
    company = forms.ModelChoiceField(queryset=Company.objects.order_by('name').all().distinct(), label='Company', widget=forms.Select(attrs={'class': 'form-control', 'name': 'company', 'id': 'company'}), required=True)
    designation = forms.CharField(label='Designation', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Designation', 'name': 'designation', 'id': 'designation'}), required=True, max_length=100)
    date_of_joining = forms.DateField(label='Joining Date', widget=forms.DateInput(attrs={'class': 'form-control', 'name': 'date_of_joining', 'id': 'date_of_joining', 'data-date-format':'yyyy-mm-dd', 'placeholder': 'YYYY-MM-DD'}), required=True)
    job_location = forms.ModelChoiceField(queryset=Location.objects.order_by('job_location').all().distinct(), label='Job Location', widget=forms.Select(attrs={'class': 'form-control', 'name': 'job_location', 'id': 'job_location'}), required=True)
    employment_setup = forms.ModelChoiceField(queryset=EmploymentSetup.objects.all().distinct(), label='Employment Setup', widget=forms.Select(attrs={'class': 'form-control', 'name': 'employment_setup', 'id': 'employment_setup'}), required=True)
    gender = forms.ModelChoiceField(queryset=Gender.objects.all().distinct(), label='Gender', widget=forms.Select(attrs={'class': 'form-control', 'name': 'gender', 'id': 'gender'}), required=True)
    marital_status = forms.ModelChoiceField(queryset=MaritalStatus.objects.all().distinct(), label='Marital Status', widget=forms.Select(attrs={'class': 'form-control', 'name': 'marital_status', 'id': 'marital_status'}), required=True)
    user_type = forms.ModelChoiceField(queryset=UserType.objects.all().distinct(), label='User Type', widget=forms.Select(attrs={'class': 'form-control', 'name': 'user_type', 'id': 'user_type'}), required=True)
    weekend_day = forms.ModelChoiceField(queryset=WeekendDay.objects.all().distinct(), label='Weekend Day', widget=forms.Select(attrs={'class': 'form-control', 'name': 'weekend_day', 'id': 'weekend_day'}), required=True)
    leave_category = forms.ModelChoiceField(queryset=LeaveCategory.objects.order_by('name').all().distinct(), label='Leave Category', widget=forms.Select(attrs={'class': 'form-control', 'name': 'leave_category', 'id': 'leave_category'}), required=True)
    single_day_entitlement = forms.CharField(label='Single Day Entitlement', widget=forms.Select(attrs={'class': 'form-control', 'name': 'single_day_entitlement', 'id': 'single_day_entitlement'}), required=True)
    annual_entitlement = forms.CharField(label='Annual Entitlement', widget=forms.Select(attrs={'class': 'form-control', 'name': 'annual_entitlement', 'id': 'annual_entitlement'}), required=True)
    reporting_manager_empid = forms.CharField(label='Manager Emp ID', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Emp ID', 'name': 'reporting_manager_empid', 'id': 'reporting_manager_empid'}), required=True, max_length=10)
    reporting_manager_name = forms.CharField(label='Manager Name', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Manager Name', 'name': 'reporting_manager_name', 'id': 'reporting_manager_name'}), required=True, max_length=100)
    reporting_manager_email = forms.EmailField(label='Manager Email', widget=forms.EmailInput(attrs={'class': 'form-control', 'type': 'email', 'placeholder': 'Manager Email', 'name': 'reporting_manager_email', 'id': 'reporting_manager_email'}), required=True, max_length=75)
    date_of_leaving = forms.DateField(label='Date of Leaving', widget=forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'YYYY-MM-DD', 'value': '1900-01-01', 'readonly': 'form-control', 'name': 'date_of_leaving', 'data-date-format':'yyyy-mm-dd', 'id': 'date_of_leaving'}), required=False)
    employee_status = forms.ModelChoiceField(queryset=EmployeeStatus.objects.all().distinct(), label='Employee Status', widget=forms.Select(attrs={'class': 'form-control', 'name': 'employee_status', 'id': 'employee_status'}), required=True)

    class Meta:
        model = EmployeeDetails
        fields = '__all__'
        exclude = ['userid']

employee/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from applyleave.models import LeaveCategory
from .forms import AddEmployeeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
import re
from employee.models import *
from django.contrib.auth.models import User
from accounts.views import *


@login_required(login_url='/login/')
def add_employee_view(request):
    context = {
        'form': AddEmployeeForm(),
        'obj_Company': Company.objects.all(),
        'obj_LeaveCategory': LeaveCategory.objects.all().order_by('name'),
        'obj_Job_Location': Location.objects.all(),
        'obj_Emp_Setup': EmploymentSetup.objects.all(),
        'obj_Gender': Gender.objects.all(),
        'obj_Marital_Status': MaritalStatus.objects.all(),
        'obj_User_Type': UserType.objects.all(),
        'obj_Weekend_Day': WeekendDay.objects.all(),
        'obj_Emp_Status': EmployeeStatus.objects.all(),
    }
    if request.method == 'POST':
        form = AddEmployeeForm(request.POST)
        if form.is_valid():
            # form.save()
            empid = re.sub(' +', ' ', request.POST.get('empid', '')).strip()
            name = re.sub(' +', ' ', request.POST.get('name', '')).strip()
            email = re.sub(' +', ' ', request.POST.get('email', '')).strip()
            company = request.POST.get('company', '')
            designation = re.sub(' +', ' ', request.POST.get('designation', '')).strip()
            date_of_joining = request.POST.get('date_of_joining', '')
            job_location = request.POST.get('job_location', '')
            employment_setup = request.POST.get('employment_setup', '')
            gender = request.POST.get('gender', '')
            marital_status = request.POST.get('marital_status', '')
            user_type = request.POST.get('user_type', '')
            weekend_day = request.POST.get('weekend_day', '')
            leave_category = request.POST.get('leave_category', '')
            single_day_entitlement = request.POST.get('single_day_entitlement', '')
            annual_entitlement = request.POST.get('annual_entitlement', '')
            reporting_manager_empid = re.sub(' +', ' ', request.POST.get('reporting_manager_empid', '')).strip()
            reporting_manager_name = re.sub(' +', ' ', request.POST.get('reporting_manager_name', '')).strip()
            reporting_manager_email = re.sub(' +', ' ', request.POST.get('reporting_manager_email', '')).strip()
            date_of_leaving = request.POST.get('date_of_leaving', '1900-01-01')
            employee_status = request.POST.get('employee_status')

            emp_obj = EmployeeDetails(empid=empid, name=name, email=email, company=company,
                                      designation=designation, date_of_joining=date_of_joining,
                                      job_location=job_location, employment_setup=employment_setup,
                                      gender=gender, marital_status=marital_status, user_type=user_type,
                                      weekend_day=weekend_day, leave_category=leave_category,
                                      single_day_entitlement=single_day_entitlement,
                                      annual_entitlement=annual_entitlement,
                                      reporting_manager_empid=reporting_manager_empid,
                                      reporting_manager_name=reporting_manager_name,
                                      reporting_manager_email=reporting_manager_email,
                                      date_of_leaving=date_of_leaving,
                                      employee_status=employee_status)

            emp_obj.save()
            context = {
                'save_message': 'Data has been Saved. !!!'
            }
            return render(request, 'add_employee.html', context)
        else:
            context = {
                'form': AddEmployeeForm(request.POST),
                'obj_Company': Company.objects.all(),
                'obj_LeaveCategory': LeaveCategory.objects.all().order_by('name'),
                'obj_Job_Location': Location.objects.all(),
                'obj_Emp_Setup': EmploymentSetup.objects.all(),
                'obj_Gender': Gender.objects.all(),
                'obj_Marital_Status': MaritalStatus.objects.all(),
                'obj_User_Type': UserType.objects.all(),
                'obj_Weekend_Day': WeekendDay.objects.all(),
                'obj_Emp_Status': EmployeeStatus.objects.all(),
            }
            return render(request, 'add_employee.html', context)
    else:
        return render(request, 'add_employee.html', context)
    # return HttpResponseRedirect(reverse(add_employee_view), context)


def employee_list_view(request):
    context = {
        'obj_emp': EmployeeDetails.objects.all().order_by('-date_of_joining'),
    }
    return render(request, 'list_employee.html', context)


def employee_details_view(request, id=None):
    context = {}
    obj_emp = EmployeeDetails.objects.get(empid=id)
    context['obj_emp'] = obj_emp
    return render(request, 'view_employee.html', context)


def employee_edit_view(request, id=None):
    context = {
        'form': AddEmployeeForm(),
        'obj_Company': Company.objects.all,
        'obj_LeaveCategory': LeaveCategory.objects.all().order_by('name'),
        'obj_Job_Location': Location.objects.all(),
        'obj_Emp_Setup': EmploymentSetup.objects.all(),
        'obj_Gender': Gender.objects.all(),
        'obj_Marital_Status': MaritalStatus.objects.all(),
        'obj_User_Type': UserType.objects.all(),
        'obj_Weekend_Day': WeekendDay.objects.all(),
        'obj_Emp_Status': EmployeeStatus.objects.all(),
    }
    obj_emp = EmployeeDetails.objects.get(empid=id)
    context['obj_emp'] = obj_emp
    if request.method == 'POST':
        form = AddEmployeeForm(request.POST, instance=obj_emp)
        context['form'] = form
        if form.is_valid():
            form.save()
            context['form'] = AddEmployeeForm(request.POST, instance=obj_emp)
            context['save_message'] = 'Updated Successfully !!!'
            return render(request, 'edit_employee.html', context)
        else:
            context['save_message'] = 'Invalid Input !!!'
            return render(request, 'edit_employee.html', context)
    return render(request, 'edit_employee.html', context)


def employee_delete_view(request, id=None):
    context = {
        'form': AddEmployeeForm(),
        'obj_Company': Company.objects.all,
        'obj_LeaveCategory': LeaveCategory.objects.all().order_by('name'),
        'obj_Job_Location': Location.objects.all(),
        'obj_Emp_Setup': EmploymentSetup.objects.all(),
        'obj_Gender': Gender.objects.all(),
        'obj_Marital_Status': MaritalStatus.objects.all(),
        'obj_User_Type': UserType.objects.all(),
        'obj_Weekend_Day': WeekendDay.objects.all(),
        'obj_Emp_Status': EmployeeStatus.objects.all(),
    }
    obj_emp = EmployeeDetails.objects.get(empid=id)
    context['obj_emp'] = obj_emp
    if request.method == 'POST':
        form = AddEmployeeForm(request.POST, instance=obj_emp)
        context['form'] = form
        obj_emp.delete()
        context['save_message'] = 'Deleted Successfully !!!'
        return render(request, 'delete_employee.html', context)
    return render(request, 'delete_employee.html', context)


@login_required(login_url='/login/')
def profile_view(request):
    context = {}
    user_obj = User.objects.get(email=request.user.email)
    obj_emp = EmployeeDetails.objects.get(email=user_obj.email)
    context['obj_emp'] = obj_emp
    return render(request, 'view_profile.html', context)

employee/templates/add_employee.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Add Employee {% endblock %}

{% block heading %} ADD EMPLOYEE {% endblock %}

{% block content %}


<form action="{% url 'add_employee' %}" method="post" autocomplete="off">
    {% csrf_token %}

    <h2><span class="badge" style="color:Green">{{ save_message }}</span></h2>
            <div class="form-group row">
                {% for field in form %}

                 {% if field.name == 'single_day_entitlement' %}
                    <div class="col-md-3 mb-2">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                        <select class="form-control" id="single_day_entitlement" name="single_day_entitlement">
                         {% for lc in obj_LeaveCategory %}
                          <option name="{{ lc.name }}" value="{{ lc.single_day_entitlement }}">{{ lc.single_day_entitlement }}</option>
                         {% endfor %}
                        </select>
                    </div>

                 {% elif field.name == 'annual_entitlement' %}
                    <div class="col-md-3 mb-2">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                        <select class="form-control" id="annual_entitlement" name="annual_entitlement">
                         {% for lc in obj_LeaveCategory %}
                          <option name="{{ lc.name }}" value="{{ lc.annual_entitlement }}">{{ lc.annual_entitlement }}</option>
                         {% endfor %}
                        </select>
                    </div>
                <!-- Below code for display rest of the field in AddEmployeeForm(ModelForm) -->
                {% else %}
                <div class="col-md-3 mb-2">
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                 {{ field }}
                </div>
                {% endif %}
                {% endfor %}
            </div>

                {% if save_message %}
                <a href="{% url 'add_employee' %}" role="button" class="btn btn-primary btn-lg">Close</a>
                {% else %}
                <button class="btn btn-primary btn-lg" type="submit">Save</button>
                {% endif %}

            <div class="form-group row">
                <div class="col-md-12 mb-2">
                <!-- Error Handling -->
                {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                <div class="alert alert-danger">
                <strong>{{ form.errors|escape }}</strong>
                </div>
                {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}
                {% endif %}
                <!-- /Error Handling -->
            </div>
            </div>

</form>


<script>
     $("#date_of_joining").datepicker({"dateFormat": "yy-mm-dd", changeMonth:true, changeYear:true, showButtonPanel:true,todayHighlight: true, autoclose: true, todayBtn: true,
        onClose: function () {
       }
    });
</script>
<script>
    var $leave_category = $( '#leave_category' ),
		$single_day_entitlement = $( '#single_day_entitlement' ),
        $annual_entitlement = $( '#annual_entitlement' ),
        $option1 = $single_day_entitlement.find( 'option' );
        $option2 = $annual_entitlement.find( 'option' );

$leave_category.on( 'change', function() {
	$single_day_entitlement.html( $option1.filter( '[name="' + this.value + '"]' ) );
  $annual_entitlement.html( $option2.filter( '[name="' + this.value + '"]' ) );
} ).trigger( 'change' );
</script>

<!--
<script>
$("#id_leave_category").change(function(){
if ($("#id_leave_category").val()=="M1"){
$("#id_single_day_entitlement").val(15);
$("#id_annual_entitlement").val(17);
}
else if ($("#id_leave_category").val()=="M2"){
$("#id_single_day_entitlement").val(15);
$("#id_annual_entitlement").val(15);
}
else if ($("#id_leave_category").val()=="M3"){
$("#id_single_day_entitlement").val(12);
$("#id_annual_entitlement").val(18);
}
else{
$("#id_single_day_entitlement").val(0);
$("#id_annual_entitlement").val(0);
}
});
</script>
-->


<!--
<div class="form-group row">

<div class="col-md-2 mb-2">
            <span class="input-text">Employee ID</span>
            <div class="form-control-plaintext">{{ form.empid }}</div>
</div>
<div class="col-md-4 mb-2">
            <span class="input-text">Name</span>
            <div class="form-control-plaintext">{{ form.name }}</div>
</div>
<div class="col-md-3 mb-2">
            <span class="input-text">Company</span>
            <div class="form-control-plaintext">{{ form.company }}</div>
</div>
<div class="col-md-3 mb-2">
            <span class="input-text">Designation</span>
            <div class="form-control-plaintext">{{ form.designation }}</div>
</div>
</div>

<div class="form-group row">

<div class="col-md-3 mb-2">
            <span class="input-text">Joining Date</span>
            <div class="form-control-plaintext">{{ form.date_of_joining }}</div>
</div>
<div class="col-md-2 mb-2">
            <span class="input-text">Work Location</span>
            <div class="form-control-plaintext">{{ form.work_location }}</div>
</div>
<div class="col-md-3 mb-2">
            <span class="input-text">Employee Setup</span>
            <div class="form-control-plaintext">{{ form.employee_setup }}</div>
</div>
<div class="col-md-4 mb-2">
            <span class="input-text">Email</span>
            <div class="form-control-plaintext">{{ form.email }}</div>
</div>
</div>

<div class="form-group row">

<div class="col-md-3 mb-2">
            <span class="input-text">Gender</span>
            <div class="form-control-plaintext">{{ form.gender }}</div>
</div>
<div class="col-md-3 mb-2">
            <span class="input-text">Marital Status</span>
            <div class="form-control-plaintext">{{ form.marital_status }}</div>
</div>
<div class="col-md-3 mb-2">
            <span class="input-text">User Type</span>
            <div class="form-control-plaintext">{{ form.user_type }}</div>
</div>
<div class="col-md-3 mb-2">
            <span class="input-text">Leave Category</span>
            <div class="form-control-plaintext">{{ form.leave_category }}</div>
</div>
</div>
<div class="form-group row">

<div class="col-md-2 mb-2">
            <span class="input-text">Manager ID</span>
            <div class="form-control-plaintext">{{ form.reporting_manager_empid }}</div>
</div>
<div class="col-md-4 mb-2">
            <span class="input-text">Manager Name</span>
            <div class="form-control-plaintext">{{ form.reporting_manager_name }}</div>
</div>
<div class="col-md-4 mb-2">
            <span class="input-text">Manager Email</span>
            <div class="form-control-plaintext">{{ form.reporting_manager_email }}</div>
</div>
<div class="col-md-2 mb-2">
            <span class="input-text">Employee Status</span>
            <div class="form-control-plaintext">{{ form.employee_status }}</div>
</div>
</div>
<button class="btn btn-primary btn-lg" type="submit">Save</button>
-->


{% endblock %}

employee/templates/delete_employee.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Delete Employee Details {% endblock %}
{% block heading %} DELETE EMPLOYEE {% endblock %}

{% block content %}

<form action="/employee/{{obj_emp.empid}}/delete/" method="post">
    {% csrf_token %}

        <div class="form-group row">

            <div class="col-md-2 mb-2">
                <span class="input-text">Employee ID</span>
                <div class="form-control">{{ obj_emp.empid }}</div>
            </div>
            <div class="col-md-4 mb-2">
                <span class="input-text">Name</span>
                <div class="form-control">{{ obj_emp.name }}</div>
            </div>
            <div class="col-md-4 mb-2">
                <span class="input-text">Email</span>
                <div class="form-control">{{ obj_emp.email }}</div>
            </div>
            <div class="col-md-2 mb-2">
                <span class="input-text">Company</span>
                <div class="form-control">{{ obj_emp.company }}</div>
            </div>
        </div>

        <div class="form-group row">

            <div class="col-md-4 mb-2">
                <span class="input-text">Designation</span>
                <div class="form-control">{{ obj_emp.designation }}</div>
            </div>
            <div class="col-md-3 mb-2">
                <span class="input-text">Joining Date</span>
                <div class="form-control">{{ obj_emp.date_of_joining }}</div>
            </div>
            <div class="col-md-2 mb-2">
                <span class="input-text">Job Location</span>
                <div class="form-control">{{ obj_emp.job_location }}</div>
            </div>
            <div class="col-md-3 mb-2">
                <span class="input-text">Employment Setup</span>
                <div class="form-control">{{ obj_emp.employment_setup }}</div>
            </div>
        </div>

        <div class="form-group row">

            <div class="col-md-3 mb-2">
                <span class="input-text">Gender</span>
                <div class="form-control">{{ obj_emp.gender }}</div>
            </div>
            <div class="col-md-3 mb-2">
                <span class="input-text">Marital Status</span>
                <div class="form-control">{{ obj_emp.marital_status }}</div>
            </div>
            <div class="col-md-3 mb-2">
                <span class="input-text">User Type</span>
                <div class="form-control">{{ obj_emp.user_type }}</div>
            </div>
            <div class="col-md-3 mb-2">
                <span class="input-text">Weekend Day</span>
                <div class="form-control">{{ obj_emp.weekend_day }}</div>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-3 mb-2">
                <span class="input-text">Leave Category</span>
                <div class="form-control">{{ obj_emp.leave_category }}</div>
            </div>
            <div class="col-md-3 mb-2">
                <span class="input-text">Single Day Entitlement</span>
                <div class="form-control">{{ obj_emp.single_day_entitlement }}</div>
            </div>
            <div class="col-md-3 mb-2">
                <span class="input-text">Annual Entitlement</span>
                <div class="form-control">{{ obj_emp.annual_entitlement }}</div>
            </div>
            <div class="col-md-3 mb-2">
                <span class="input-text">Manager ID</span>
                <div class="form-control">{{ obj_emp.reporting_manager_empid }}</div>
            </div>
        </div>


        <div class="form-group row">
            <div class="col-md-4 mb-2">
                <span class="input-text">Manager Name</span>
                <div class="form-control">{{ obj_emp.reporting_manager_name }}</div>
            </div>
            <div class="col-md-4 mb-2">
                <span class="input-text">Manager Email</span>
                <div class="form-control">{{ obj_emp.reporting_manager_email }}</div>
            </div>
            <div class="col-md-2 mb-2">
                <span class="input-text">Date of Leaving</span>
                <div class="form-control">{{ obj_emp.date_of_leaving }}</div>
            </div>
            <div class="col-md-2 mb-2">
                <span class="input-text">Employee Status</span>
                <div class="form-control">{{ obj_emp.employee_status }}</div>
            </div>
        </div>

         <div class="form-group row">
            <div class="col-md-3 mb-2">
                <button class="btn btn-danger btn-lg" type="submit">Delete</button>
                <a href="{% url 'employee_list' %}" role="button" class="btn btn-primary btn-lg">Back</a>
            </div>
            <div class="col-md-9 mb-2">
                <h2 align="left"><span class="badge" style="color:Red">{{ save_message }}</span></h2>
            </div>
         </div>


</form>

    {% endblock %}

employee/templates/thanks.html
{% extends 'base.html' %}
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %} Thank You {% endblock %}</title>
</head>
<body>
{% block content %}
<h1>Thank You !!!</h1>

{% endblock %}
</body>
</html>